### ISSUE TITLE
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "VectorCalculationsThread 10"

### ISSUE THREAD

**Issue by loretoparisi** [deeplearning4j/nd4j#1785]
#### Issue Description

This was the stdout before the issued happened:

```
2017-04-21 16:51:55,178  INFO [main] (Nd4jBackend.java:194) - Loaded [CpuBackend] backend
2017-04-21 16:51:55,271  INFO [main] (NativeOpsHolder.java:49) - Number of threads used for NativeOps: 6
2017-04-21 16:51:55,307 DEBUG [main] (Reflections.java:186) - going to scan these urls:
jar:file:/musixmatch/jar/MXMDeepLearningDL4J.jar!/
2017-04-21 16:51:55,507  INFO [main] (Reflections.java:229) - Reflections took 197 ms to scan 1 urls, producing 29 keys and 189 values 
2017-04-21 16:51:55,698  INFO [main] (Nd4jBlas.java:36) - Number of threads used for BLAS: 6
2017-04-21 16:51:55,705  INFO [main] (DefaultOpExecutioner.java:544) - Backend used: [CPU]; OS: [Linux]
2017-04-21 16:51:55,706  INFO [main] (DefaultOpExecutioner.java:545) - Cores: [12]; Memory: [8.7GB];
2017-04-21 16:51:55,706  INFO [main] (DefaultOpExecutioner.java:546) - Blas vendor: [OPENBLAS]
2017-04-21 16:52:00,456 DEBUG [Thread-10] (WordVectorSerializer.java:2336) - Trying full model restoration...
2017-04-21 16:52:06,403  INFO [Thread-10] (WordVectorSerializer.java:2821) - Projected memory use for model: [18.04 MB]
2017-04-21 16:52:20,539  INFO [Thread-10] (SequenceVectors.java:127) - Starting vocabulary building...
2017-04-21 16:52:20,539 DEBUG [Thread-10] (VocabConstructor.java:180) - Target vocab size before building: [0]
2017-04-21 16:52:20,543 DEBUG [Thread-10] (VocabConstructor.java:197) - Trying source iterator: [0]
2017-04-21 16:52:20,543 DEBUG [Thread-10] (VocabConstructor.java:198) - Target vocab size before building: [0]
2017-04-21 16:52:43,803 DEBUG [Thread-10] (VocabConstructor.java:286) - Wating till all processes stop...
2017-04-21 16:52:43,810 DEBUG [Thread-10] (VocabConstructor.java:296) - Vocab size before truncation: [70211],  NumWords: [5654882], sequences parsed: [150], counter: [5654739]
2017-04-21 16:52:43,874 DEBUG [Thread-10] (VocabConstructor.java:389) - Scavenger: Words before: 70211; Words after: 23784;
2017-04-21 16:52:43,874 DEBUG [Thread-10] (VocabConstructor.java:303) - Vocab size after truncation: [23784],  NumWords: [5573770], sequences parsed: [150], counter: [5654739]
2017-04-21 16:52:52,814  INFO [Thread-10] (VocabConstructor.java:372) - Sequences checked: [150], Current vocabulary size: [23784]; Sequences/sec: [4.65];
2017-04-21 16:52:52,815  INFO [Thread-10] (WordVectorSerializer.java:2821) - Projected memory use for model: [54.44 MB]
2017-04-21 16:52:52,884  INFO [Thread-10] (InMemoryLookupTable.java:141) - Initializing syn1...
2017-04-21 16:52:52,915  INFO [Thread-10] (SequenceVectors.java:160) - Building learning algorithms:
2017-04-21 16:52:52,915  INFO [Thread-10] (SequenceVectors.java:168) -           building SequenceLearningAlgorithm: [PV-DBOW]
2017-04-21 16:52:52,917  INFO [Thread-10] (SequenceVectors.java:176) -           building ElementsLearningAlgorithm: [SkipGram]
2017-04-21 16:52:52,917  INFO [Thread-10] (SequenceVectors.java:273) - Starting learning process...
```

The full stacktrace is [here](https://gist.github.com/silvioOlivastri/b752a1c3cd85f6f31dd693de2d303586)

```
Exception in thread "VectorCalculationsThread 0" Exception in thread "VectorCalculationsThread 10" Exception in thread "VectorCalculationsThread 1" Exception in thread "VectorCalculationsThread 4" java.lang.OutOfMemoryError: Java heap space
        at org.bytedeco.javacpp.Pointer.<init>(Pointer.java:83)
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:134)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "VectorCalculationsThread 10"
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
        at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:49)
        at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:21)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:273)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:215)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:171)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
java.lang.OutOfMemoryError: Java heap space
        at org.nd4j.linalg.api.ops.aggregates.BaseAggregate.<init>(BaseAggregate.java:15)
        at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:31)
        at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:21)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:273)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:215)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:171)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
java.lang.OutOfMemoryError: Java heap space
        at java.lang.Double.valueOf(Double.java:519)
        at org.nd4j.linalg.api.ops.aggregates.BaseAggregate.<init>(BaseAggregate.java:20)
        at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:31)
        at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:21)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:273)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:215)
        at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:171)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
Exception in thread "VectorCalculationsThread 8" java.lang.OutOfMemoryError: Java heap space
```

We are using at launch the env

`ENV MALLOC_ARENA_MAX 4`

and

`-Xmx10000m -XX:+UseParallelGC -XX:-UseGCOverheadLimit`

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
  0.8.0

* platform information (OS, etc)
  Docker + Ubuntu 16.0.4 LTS

* CUDA version, if used
  none
* NVIDIA driver version, if in use
  none

We are aware of an issue of a possible memory leak of the JVM/JRE inside Docker, so this could be related to https://github.com/moby/moby/issues/15020

**Comment by raver119** [comment]
Can you run your code outside of docker?

**Comment by loretoparisi** [comment]
@raver119 We are investigating now this, since we have other java libs (CoreNLP) running smoothly within Docker, we are now enabling dump and adding further logging here, please wait.

**Comment by raver119** [comment]
also, please get rid of 2 this params: `-XX:+UseParallelGC -XX:-UseGCOverheadLimit`

**Comment by loretoparisi** [comment]
@raver119 do you mean to avoid to use them?

**Comment by huitseeker** [comment]
Yes.

**Comment by loretoparisi** [comment]
Thanks we are running directly in Ubuntu 16.0.4 LTS, let's see what happens.

**Comment by raver119** [comment]
any news guys?

**Comment by huitseeker** [comment]
This seems to work https://twitter.com/loretoparisi/status/855489627871997952

@loretoparisi Would you mind documenting precisely your memory setup so that we can find this one if it occurs again ? We'd need physical memory available, JVM parameters at launch, and ideally the source Docker image you were using, and if other containers were running on the machine (also,  any unusual cgroup parameters if any).

**Comment by loretoparisi** [comment]
So, the physical available memory is 16GB. The cpu is a Intel Xeon with 8 cores. The GPU (not uses in this case) are 2 Nvidia GeForce 1080.
We are testing the run outside Docker right now, please wait we will back with results.
All investigation let to think that this is related to a Docker issue with Java settings, but we are not 100% sure, before getting results from the run in Ubuntu.

		

		Get Outlook for iOS
	_____________________________

**Comment by loretoparisi** [comment]
@huitseeker thanks for your help, we have reported this issue to Docker/moby, since it seems to be related to a combination of factors between Docker, Linux and Java, as several evidences show, and other similar issues referring OOM, memory leaks, GC issues, etc.
I have collected all the info we have at this point, and hopefully get a solution here!

**Comment by silvioOlivastri** [comment]
Hi guys,

I run the same code on my computer (MacOS with IntellyJIDEA) without docker and I have the same issues.


```
12:41:17.153 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Target vocab size before building: [0]
12:41:17.153 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Trying source iterator: [0]
12:41:17.153 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Target vocab size before building: [0]
12:41:43.625 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Wating till all processes stop...
12:41:43.638 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Vocab size before truncation: [69546],  NumWords: [5658961], sequences parsed: [150], counter: [5658812]
12:41:43.736 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Scavenger: Words before: 69546; Words after: 23731;
12:41:43.736 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Vocab size after truncation: [23731],  NumWords: [5578790], sequences parsed: [150], counter: [5658812]
12:41:55.677 [main] INFO  o.d.m.w.wordstore.VocabConstructor - Sequences checked: [150], Current vocabulary size: [23731]; Sequences/sec: [3.89];
12:41:55.677 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Projected memory use for model: [54.32 MB]
12:41:55.803 [main] INFO  o.d.m.e.inmemory.InMemoryLookupTable - Initializing syn1...
12:41:55.871 [main] INFO  o.d.m.s.SequenceVectors - Building learning algorithms:
12:41:55.871 [main] INFO  o.d.m.s.SequenceVectors -           building SequenceLearningAlgorithm: [PV-DBOW]
12:41:55.873 [main] INFO  o.d.m.s.SequenceVectors -           building ElementsLearningAlgorithm: [SkipGram]
12:41:55.873 [main] INFO  o.d.m.s.SequenceVectors - Starting learning process...
Exception in thread "VectorCalculationsThread 1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.bytedeco.javacpp.Pointer.<init>(Pointer.java:83)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:84)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:853)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:916)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:176)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
Exception in thread "VectorCalculationsThread 2" Exception in thread "VectorCalculationsThread 0" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:49)
	at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:21)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:273)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:215)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:171)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
Exception in thread "VectorCalculationsThread 3" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.nd4j.linalg.api.ops.aggregates.BaseAggregate.<init>(BaseAggregate.java:17)
	at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:31)
	at org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:21)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:273)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:215)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:171)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:867)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:916)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:176)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
13:19:22.022 [main] INFO  o.d.m.s.SequenceVectors - Epoch: [1]; Words vectorized so far: [330431];  Lines vectorized so far: [8]; learningRate: [1.0E-4]
13:19:22.027 [main] INFO  o.d.m.s.SequenceVectors - Time spent on training: 2246154 ms
```

the process ends, but during training (towards the end) it generates the error.

Ps: 
- java options: `-Xmx6096m`
- DL4J 0.8.0

**Comment by raver119** [comment]
So, to be clear i have full picture:

You have 150 documents, that are pretty big, total number of words in them 5658961, that is over 30k words per document. 

Is that right?

**Comment by silvioOlivastri** [comment]
Yes,

this is a list of bytes for documents:

```
421444
249191
219447
194504
189205
256930
277615
9213
457026
206989
164136
274170
248763
397965
387589
338711
138704
186301
176580
341769
292862
104474
720548
483972
85291
189924
107998
317284
53175
357864
265972
126917
261711
166198
107776
148389
76166
438136
199964
247937
212330
297942
281270
50708
319681
207567
197229
88466
426991
127050
133561
221187
205460
226542
46298
229513
272800
211847
156433
497760
203695
194232
180754
250869
48900
11909
304941
192749
274922
542491
164059
284845
281407
172305
163607
161062
104781
406640
182510
227050
```

**Comment by loretoparisi** [comment]
Adding that if this analysis is correct i.e. *150 documents for a total of 5658961 words*

and the exception takes place in the `ArrayList` while adding:

 ```
at java.util.Arrays.copyOf(Arrays.java:3181)
    at java.util.ArrayList.grow(ArrayList.java:261)
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
    at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
    at java.util.ArrayList.add(ArrayList.java:458)
```

this means that something occurs while calling

```
org.nd4j.linalg.api.ops.aggregates.impl.AggregateSkipGram.<init>(AggregateSkipGram.java:49)
```

like it cannot hold a document of that size?

**Comment by silvioOlivastri** [comment]
Other info:

```
BEFORE PRE-PROCESS
WORDS NUMBER: 6167000
AVG WORDS NUMBER FOR DOC: 41113

AFTER PRE-PROCESS
TOKENS NUMBER: 5658812
AVG TOKENS NUMBER FOR DOC: 37725
```

PRE-PROCESS = Tokenizations

**Comment by raver119** [comment]
Right, logic flaw. Fix incoming, but will be merged slightly later

**Comment by loretoparisi** [comment]
@raver119 that sounds great! to be clear, was it an issue in the *iterateSample* ?

**Comment by raver119** [comment]
Fix applied. Will be merged later.

TL/DR: purge of batches happens at document's end. But if you have huge docuemts - that will lead to huge batches. So, internally batches should be dispatched in such cases.

**Comment by raver119** [comment]
Thanks for highlighting this issue.

**Comment by loretoparisi** [comment]
@raver119 ok thanks a lot, waiting the fix then to procede with the complete training! Very glad to help you and come to a solution so quickly!

**Comment by loretoparisi** [comment]
@raver119 sorry do you have a eta for this fix te be on maven? Thanks a lot for your help guys!

**Comment by agibsonccc** [comment]
@loretoparisi no - just use snapshots for now. We don't guarantee a release cycle for the open source.

**Comment by loretoparisi** [comment]
@agibsonccc I perfectly understand, so we can go simply to the master?

**Comment by silvioOlivastri** [comment]
@agibsonccc I should use `0.8.1-SNAPSHOT`?

**Comment by agibsonccc** [comment]
Yes, with the snapshot repo: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/pom.xml#L16

**Comment by silvioOlivastri** [comment]
Ok, now everything works well :)

**Comment by raver119** [comment]
Great, thanks for highlighting this issue

**Comment by yanhuixie** [comment]
It may be the result of glibc...
http://codearcana.com/posts/2016/07/11/arena-leak-in-glibc.html
https://www.ibm.com/developerworks/community/blogs/kevgrig/entry/linux_glibc_2_10_rhel_6_malloc_may_show_excessive_virtual_memory_usage?lang=en
https://github.com/cloudfoundry/java-buildpack/issues/320
