### ISSUE TITLE
CUDA Error Code = 77

### ISSUE THREAD

**Issue by wanjizheng** [deeplearning4j/nd4j#2740]
#### Issue Description
Trying to train a LSTM network similar to the Word2VecSentimentRNN example.  Main code shows below:
https://gist.github.com/wanjizheng/1b7b736eb3933f75bec131bdb095b0c0
https://gist.github.com/wanjizheng/50485900d31142f4bfd87808e80647a5

However, if I use GPU then get the following error:
https://gist.github.com/wanjizheng/74bccd5bd0f976172735e1e362114d37

If I switch to CPU then it works fine.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.1
* platform information (OS, etc) 
    OS: Red Hat
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               2100.000
BogoMIPS:              4199.40
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31

84:00.0 3D controller [0302]: NVIDIA Corporation GK210GL [Tesla K80] [10de:102d] (rev a1)
	Subsystem: NVIDIA Corporation Device [10de:106c]
	Flags: bus master, fast devsel, latency 0, IRQ 130
	Memory at fa000000 (32-bit, non-prefetchable) [size=16M]
	Memory at 27800000000 (64-bit, prefetchable) [size=16G]
	Memory at 27c00000000 (64-bit, prefetchable) [size=32M]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nvidia, nvidia-drm, nouveau, nvidiafb

85:00.0 3D controller [0302]: NVIDIA Corporation GK210GL [Tesla K80] [10de:102d] (rev a1)
	Subsystem: NVIDIA Corporation Device [10de:106c]
	Flags: bus master, fast devsel, latency 0, IRQ 131
	Memory at f9000000 (32-bit, non-prefetchable) [size=16M]
	Memory at 27000000000 (64-bit, prefetchable) [size=16G]
	Memory at 27400000000 (64-bit, prefetchable) [size=32M]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nvidia, nvidia-drm, nouveau, nvidiafb

* CUDA version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by AlexDBlack** [comment]
Thanks.
OK, so the first thing here: we've hada  few workspace-related fixes since 0.9.1 - the bugs for which *might* be able to cause this.

As a first step, I can recommend trying snapshots and see if it runs correctly - see here for details: https://deeplearning4j.org/snapshots

Note that there have been a small number of API changes since then. You can take a look at this PR/branch for the examples for that: https://github.com/deeplearning4j/dl4j-examples/pull/589

Unrelated, but FYI: you'll get better performance with LSTM (instead of GravesLSTM) as it supports CuDNN.

**Comment by wanjizheng** [comment]
Thanks @AlexDBlack for your swift reply. I thought it might be workspace related, and therefore already comment out the related lines in the code.  I've tried the snapshots version before (for a different reason) but it never worked for me... Will try again and let you know

**Comment by wanjizheng** [comment]
@AlexDBlack Followed your suggestion and changed to the snapshots version.  Still doesn't work but with a different error message log:
https://gist.github.com/wanjizheng/4f3e2b69942b8c6bc2a1d37704935d9e

**Comment by wanjizheng** [comment]
Ok, after I upgrade to the snapshots, it seems that the CPU approach stop working as well.  See the below error log 
https://gist.github.com/wanjizheng/231576cb26029e83f2c39a3a12bd8282

**Comment by wanjizheng** [comment]
I think I know what's going wrong here.  The SNAPSHOTS upgrade works, however I also change the GravesLSTM to LSTM as @AlexDBlack  suggested, and that create this problem.  If I use SNAPSHOTS with the GravestLSTM, then it works fine.

**Comment by raver119** [comment]
Can you please test current snapshot (1.0.0-SNAPSHOT) and tell us if problem is finally fixed for you?

**Comment by raver119** [comment]
Feel free to reopen this issue if problem is still reproducible.
